DROP DATABASE IF EXISTS DBStructureDesign;
CREATE DATABASE todoapp_db;
USE todoapp_db; 

CREATE TABLE users	
(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	user_password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);



CREATE TABLE user_tasks
(
	user_task VARCHAR(255) DEFAULT "NO TASK",
	task_datetime VARCHAR(255),
	created_at TIMESTAMP DEFAULT NOW(),
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
	ON DELETE CASCADE
);


